version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/rdsauth
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "checksums.txt"
